FROM python:3.8.3-alpine

ENV HOME=/usr/src/app
ENV APP_HOME=$HOME/backend
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR $APP_HOME

RUN apk update && \
    apk add zlib-dev jpeg-dev postgresql-dev gcc python3-dev musl-dev && \
    apk add --update alpine-sdk && apk add libffi-dev openssl-dev cargo rust

RUN pip install --upgrade pip && \
    pip install pipenv

COPY . .

RUN pipenv install --system --deploy

ENTRYPOINT ["/usr/src/app/backend/docker-entrypoint.prod.sh"]